# Generated by Django 3.1.7 on 2021-04-11 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_article_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='author',
        ),
    ]
